### ISSUE TITLE
Design config options for mongo-knex

### ISSUE THREAD

**Issue by kirrg001** [NexesJS/mongo-knex#4]
## Problem

Projects want to use NQL and want to forward information about database tables, in particular database relations.

## Goal

Design a config options which makes it possible to query the database based on this config object.
How do we pass the table information to mongo-knex?

## Tasks

- [x] look at how GQL did it (https://github.com/TryGhost/GQL/blob/master/lib/context.js)
- [x] collect the information mongo-knex needs from the project
- [x] post example design
- [x] add code to receive the options
- [x] change config keys to new format

**Comment by gargol** [comment]
The naming of variables should def be more consistent e.g.: `tableNameAs` an `join_table`. Preferable should stay camelCase as these are only used within JavaScript code :)
