### ISSUE TITLE
Support and/or conjunction for relations

### ISSUE THREAD

**Issue by kirrg001** [NexesJS/mongo-knex#5]
## Description

NQL should support and/or conjunctions for relations.

The SQL strategy is currently covered in https://github.com/NexesJS/NQL/issues/1

e.g. You can pass a filter into NQL `filter=tag:en+tag:de` and mongo-knex will receive a mongo JSON object and needs to interpret this object with the help of #4. It has to attach the correct SQL queries.

## Tasks

- [x] support one or some cases for OR conjunction case
- [x] support one or some cases for AND conjunction case
- [x] support all cases for OR conjunction
- [x] support all cases for AND conjunction

**Comment by kirrg001** [comment]
We just merged #18, which supports a couple of more cases for $and and $or conjunction.

I am closing this issue for now. If we discover new cases which are not covered, we just raise a new issue 👍
