### ISSUE TITLE
Support negation

### ISSUE THREAD

**Issue by kirrg001** [NexesJS/mongo-knex#7]
## Description

NQL should support negation.
There are various combinations where you can use negation.

e.g. You can pass a filter into NQL 

- `filter=-slug:en` (same table negation)
- `filter=-tag:en+-tag:de` (negation for relations)

mongo-knex has to receive mongo JSON objects and interpret the object correctly.

## Tasks

- [x] support one case
- [x] add implementation for relation negation
- [x] add implementation same table negation

Add a test case and the assertion first and see if it passes.

**Comment by gargol** [comment]
We need more test coverage for `same table negation` case, but it seems to work right now just needs verificaton
